name: Publish to development (snapshot) repo
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@093dfe9d598ec5a42246855d09b49dc76803c005
        with:
          arguments: publishMavenPublicationToDevelopmentRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
          COMMIT_HASH: ${{ steps.commit.outputs.hash }}
          COMMIT_HASH_SHORT: ${{ steps.commit.outputs.short }}
