name: Publish to development (snapshot) repo
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6
      - name: Publish package
        uses: gradle/gradle-build-action@680037c65b998d750280aefaffd22cd3560fc9db
        with:
          arguments: publishMavenPublicationToDevelopmentRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
          COMMIT_HASH: ${{ steps.commit.outputs.hash }}
          COMMIT_HASH_SHORT: ${{ steps.commit.outputs.short }}
